### ISSUE TITLE
Problem handling final \n char from rbw

### ISSUE THREAD

**Issue by cstrahan** [fdw/rofi-rbw#14]
Looks like `rofi-rbw` trips on the final `\n` character at the end of the password text from `rbw`:

```
Traceback (most recent call last):
  File "/home/cstrahan/.local/bin/rofi-rbw", line 8, in <module>
    sys.exit(main())
  File "/home/cstrahan/.local/lib/python3.8/site-packages/rofi_rbw/rofi_rbw.py", line 187, in main
    RofiRbw().main()
  File "/home/cstrahan/.local/lib/python3.8/site-packages/rofi_rbw/rofi_rbw.py", line 134, in main
    data = self.get_credentials(selected_entry.strip(), selected_folder.strip())
  File "/home/cstrahan/.local/lib/python3.8/site-packages/rofi_rbw/rofi_rbw.py", line 183, in get_credentials
    return Credentials(result)
  File "/home/cstrahan/.local/lib/python3.8/site-packages/rofi_rbw/credentials.py", line 13, in __init__
    key, value = line.rsplit(": ", 1)
ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by fdw** [comment]
Thanks for noticing that! Should be fixed on `main` now 🙂

**Comment by ilyazzz** [comment]
@fdw could you make a hotfix release for this? The AUR package is broken right now since it follows stable releases.

**Comment by fdw** [comment]
I assume this means that the fix works. Release is on its way :)

**Comment by ilyazzz** [comment]
Thank you, the fix does indeed work.
