### ISSUE TITLE
Can't open rofi-rbw outside terminal

### ISSUE THREAD

**Issue by nozerorma** [fdw/rofi-rbw#96]
I'm on plasma 6 using wayland (Tuxedo OS 3). Rofi-rbw works perfectly fine when launched from terminal, but it wont open from krunner, shortcut or else. 

I've tried using rofi, wofi and the rofi-wayland fork, also using ydotool and dotool and no dice. 
FWIW rofi-wayland does run with no problem when called from inside terminal, and rofi-rbw still runs fine on x11 as well.

**Comment by fdw** [comment]
Have you tried configuring the `selector`, `typer` and `clipboarder`? Does that change anything? Can you get a log from somewhere?

It sounds to me like a problem with the environment, but I'm not familiar with KDE, unfortunately.

**Comment by nozerorma** [comment]
Sorry for the typo, I meant that it run fine from the terminal. Found the culprit also! It was rbw, not the frontend. 
Seems that Wayland didn't like the cargo install. Installed the deb package and its rocking again. It's an amazing tool, thanks.

Traceback (most recent call last):
  File "/usr/local/bin/rofi-rbw", line 8, in <module>
    sys.exit(main())
  File "/home/miguel/.local/lib/python3.10/site-packages/rofi_rbw/__main__.py", line 5, in main
    RofiRbw().main()
  File "/home/miguel/.local/lib/python3.10/site-packages/rofi_rbw/rofi_rbw.py", line 160, in main
    entries = self.rbw.list_entries()
  File "/home/miguel/.local/lib/python3.10/site-packages/rofi_rbw/rbw.py", line 12, in list_entries
    rbw = run(["rbw", "list", "--fields", "folder,name,user"], encoding="utf-8", capture_output=True)
  File "/usr/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'rbw'

**Comment by fdw** [comment]
Thank you! 😊
