### ISSUE TITLE
Issue with entry incorrectly formatted

### ISSUE THREAD

**Issue by MrHoz** [fdw/rofi-rbw#98]
After I gain the permission on a voluminous folder for my enterprise, i started getting the following error.
I quickly checked all entry's name, without seeing any big problem.

```
[~] rofi-rbw                                                                                                                                                                                              16:51:18
Traceback (most recent call last):
  File "/home/user/.local/pipx/venvs/rofi-rbw/lib/python3.11/site-packages/rofi_rbw/rbw.py", line 28, in __parse_rbw_output
    return Entry(fields[1], fields[0], fields[2] if len(fields) > 2 else "")
                 ~~~~~~^^^
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.local/bin/rofi-rbw", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/user/.local/pipx/venvs/rofi-rbw/lib/python3.11/site-packages/rofi_rbw/__main__.py", line 5, in main
    RofiRbw().main()
  File "/home/user/.local/pipx/venvs/rofi-rbw/lib/python3.11/site-packages/rofi_rbw/rofi_rbw.py", line 24, in main
    entries = self.rbw.list_entries()
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/pipx/venvs/rofi-rbw/lib/python3.11/site-packages/rofi_rbw/rbw.py", line 20, in list_entries
    [self.__parse_rbw_output(it) for it in (rbw.stdout.strip("\n").split("\n"))],
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/pipx/venvs/rofi-rbw/lib/python3.11/site-packages/rofi_rbw/rbw.py", line 20, in <listcomp>
    [self.__parse_rbw_output(it) for it in (rbw.stdout.strip("\n").split("\n"))],
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/pipx/venvs/rofi-rbw/lib/python3.11/site-packages/rofi_rbw/rbw.py", line 30, in __parse_rbw_output
    raise Exception("Entry is incorrectly formatted and cannot be parsed")
Exception: Entry is incorrectly formatted and cannot be parsed                                                         
```

Is there a way to skip malformed entries, or to have more info on the problematic one ?

**Comment by fdw** [comment]
I've just pushed something to improve the error message and show the problematic entry. Maybe you can try it to find your problem?

Alternatively, you can see if `rbw list --fields folder,name,user` turns up something weird.

**Comment by MrHoz** [comment]
Thanks for the quick update !

The issue was with an entry with a dot (like '.username').  The script was reading it as the following:
```
Exception: Entry '$username' cannot be parsed
```

Changed the entry to remove the dot, and it's working like a charm !

**Comment by MrHoz** [comment]
I tried adding the period back, but I can't reproduce it neither, period is working fine now 😕
No Folder
Username: .username (no special character)
pass: some.pass (no special character)

My assumption is that the `rbw sync` that I did after removing the period in the entry in the bitvault fixed the issue locally, since I did not think of doing that before opening this issue.

**Comment by fdw** [comment]
Thanks for trying! At least there's no a better error message 😉
